@ Generated by gcc 3.0 for ARM/elf
	.file	"native_codegen.c"
	.code	16
	.text
	.align	2, 0
	.global	NativeCodegen
	.thumb_func
	.type	NativeCodegen,function
NativeCodegen:
	push	{r5, r6, lr}
	ldr	r3, .L2
	mov	r2, #13
	eor	r3, r3, r0
	mov	r5, r3
	mul	r5, r5, r2
	mov	r6, r1
	str	r5, [r6]
	mov	r0, r5
	mov	r1, #10
	bl	__udivsi3
	str	r0, [r6, #4]
	mov	r0, r5
	bl	External
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L3:
	.align	2, 0
.L2:
	.word	-1985229329
.Lfe1:
	.size	NativeCodegen,.Lfe1-NativeCodegen
